version: '3.2'

networks:
  postgres-network:
    driver: bridge

services:
    POSTGRES:
      container_name: container_postgres
      image: postgres
      environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        PGDATA: /data/postgres
      # volumes:
      #   - ~/postgres:/data/postgres
      ports:
        - 5432:5432
      networks:
        - postgres-network
      restart: unless-stopped

    PGADMIN:
      container_name: container_pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
        PGADMIN_DEFAULT_PASSWORD: 'admin'
      # volumes:
      #   - ~/pgadmin:/var/lib/pgadmin
      ports:
        - 16543:80
      networks:
        - postgres-network
      depends_on:
        - POSTGRES
      restart: unless-stopped